ButcherBrosQualityMeat/ButcherBros

README.md

dalton edited the Readme

---

server/db/models/index.js
server/db/models/product.js

I have created product.js in the server/models folder as well as created associations in the index.js file in the same folder

Add product model

---

server/db/models/index.js
server/db/models/order.js

Create Order model

---

server/db/models/product.js

fixed decimal issue

---

server/db/models/temp.md
server/db/models/user.js

11 Added user models. and temp.md for notes

---

script/seed.js
server/db/models/product.js
server/db/models/user.js

updated user model and seed file to corelate to eachother

---

client/app.js
client/components/footer.js
client/components/index.js

Created Footer Component to display on each page of site

Feature: Create Footer React Component

---

script/seed.js
server/db/models/category.js
server/db/models/index.js

changed the seed data and added a Category table

---

server/api/index.js
server/api/products.js
server/index.js

Api routes

---

client/components/HomePage.js
client/components/index.js
client/routes.js

(feat) added homepage user view

---

server/api/categories.js
server/api/index.js
server/api/products.js

added category routes

---

client/store/index.js
client/store/product.js

(feat) added product.js store and added to index

---

client/routes.js
client/store/index.js
client/store/product.js
server/api/categories.js

Updated store to reflect only allCategories and allProducts, updated all categories route to eager load products, Frank mapped dispatch to props on the Routes component

Make initial fetch requests

---

client/index.js

added browser router

---

client/components/SinglePageView.js

and fixed formatting (adjustable size pic now based on device)

(fix) Single page View displays meat for specified product id

---

client/components/AllProducts.js

feat: add to cart button on AllProducts component

---

client/components/AllProducts.js
client/store/cart.js

- Cart reducer now properly populates `contents` array when adding an item that was previously in the cart

Bugfix: Cart reducer fixed

---

client/components/cart/cartPresentational.js

- Made cart page bearable to look at and at least marginally useful
- Price reflects total number of items in cart

Style: Update Cart View

---

client/store/cart.js
server/api/cart.js
server/api/index.js

Thunks created to store and fetch cart from req.session on server.
To implement this functionality:
- Make initial call to retrieve cart upon loading of page
- Update cart on cookie after items are added to the redux store cart.

Feature: Create Thunks to store cart on req.session

---

package-lock.json
package.json
server/api/index.js
server/api/stripe.js
server/index.js

unable to test with front end yet, changes probably need to be made for functionality

feat: added stripe backend

---

client/components/AllProducts.js
client/store/product.js
package.json
server/db/models/product.js
tests/ProductSlice.js
tests/setup.js

added a script to package.json to run test
created a tests folder
*might have to npm install again to run the tests* - I am using chai

feat: test a vertical slice

---

client/components/AllProducts.js
client/components/cart/cartPresentational.js
client/components/navbar.js
client/routes.js
script/seed.js

feat: added dynamic cart item in navbar

---

server/api/cart.js
server/api/index.js
server/api/orders.js
server/db/models/order.js

Implemented ability to **POST** order to server.
- new server route created: /api/orders
- **POST** request creates a new order in the order table and returns the newly created instance
- added "address" field to Order model

Feat: Create route: /api/orders

---

client/components/navbar.js

made the user route to homepage when log out is clicked

chore: fixed route for logout

---

client/components/footer.js
client/components/navbar.js

footer and header capitalized and slight changes inside file

Navbar footer correction

---

server/api/stripe.js

chore: remove dead code

---

client/index.js
client/routes.js
client/store/user.js
server/api/cart.js

chore: fixed routes and changed from BrowserRouter

---

client/components/SingleCategory.js

chore: fix price display again

---

client/components/SingleCategory.js

fix: prices and shapes

---

client/store/cart.js
server/api/cart.js

Eliminated circular imports between `store.js` and `cart.js`. Updating cart now occurs server side.

Refactor: Eliminate circular logic in cart.js

---

client/components/HomePage.js
public/style.css
script/seed.js
server/db/models/category.js

also edited category model to include a carousel image and seeded it

Feat: feat: dynamically rendered category carousel

---

client/components/CheckoutForm.js
server/api/stripe.js

chore: hide the Stripe keys, watch for overwrite of mapState on CheckoutForm

---

client/components/CheckoutForm.js
server/api/orders.js

chore:  fixed checkoutform component to render order view

---

client/components/CheckoutForm.js

Fixed Date being sent to order

---

client/components/Cart.js
client/components/CheckoutForm.js
client/components/OrderView.js
client/store/cart.js
server/api/cart.js
server/api/orders.js

- Thunk created to clear `cart` on the session object, then update local cart as an empty cart
- Add `Empty Cart` button to checkout page (only renders if cart is populated)
- Local `cart` is emptied upon loading order view page

Clear cart functionality

---

client/components/Navbar.js
client/components/SingleCategory.js

feat: dynamic categories from navbar dropdown

---

client/components/SingleCategory.js
client/store/product.js
package.json
server/api/categories.js
server/db/models/category.js
tests/CategorySlice.js

Category tests

---

client/components/SingleCategory.js
client/store/product.js

chore: removed console logs, added keys for mapping

---

client/components/Cart.js
client/components/CartView.js
client/components/CheckoutForm.js
client/components/HomePage.js
client/components/SinglePageView.js

some last minute stylezz

---

client/components/Navbar.js
public/style.css

Should be showing all categories from the dropdown and the cursor/pointer should be correct

chore/feature/bug: hopefully fixed the navbar for good. see comments for details

---

client/components/AllProducts.js
client/components/Cart.js
client/components/CheckoutForm.js
client/components/SingleCategory.js

style: changed some fonts
